// Données de seed — indépendant de Vite, images en chemins directs
export const seedArticles = [
  {
    slug: 'les-meilleures-solutions-anti-nuisibles-pour-votre-entreprise',
    title: 'Les meilleures solutions anti-nuisibles pour votre entreprise',
    date: '11 Déc. 2025', category: 'Anti-nuisibles pour entreprises', readMinutes: 5,
    image: '/nuisibles-solution-pro.png',
    content: {
      introHeading: 'Pourquoi la lutte anti-nuisibles est essentielle pour votre entreprise',
      introParagraph: 'Une infestation de nuisibles dans vos locaux professionnels peut nuire à la santé, à la réputation et à la pérennité de votre activité. Faire appel à des professionnels permet de prévenir les risques, de respecter la réglementation et de protéger vos employés et vos clients. Voici les points clés à retenir.',
      numberedItems: [
        { title: 'Risques sanitaires et sécuritaires', text: 'Rongeurs, insectes et autres nuisibles peuvent contaminer les denrées, transmettre des maladies ou provoquer des allergies. Dans un contexte professionnel, les conséquences peuvent être lourdes : fermeture administrative, perte de confiance des clients, absentéisme.' },
        { title: 'Protéger la réputation de votre entreprise', text: "Une seule alerte ou un signalement peut suffire à entacher l'image de votre société. Une lutte anti-nuisibles proactive et documentée montre votre sérieux et rassure vos partenaires et vos clients." },
        { title: 'Conformité réglementaire', text: "Les établissements recevant du public, les métiers de l'alimentaire et de la santé sont soumis à des obligations en matière d'hygiène et de lutte contre les nuisibles. Des rapports et des interventions régulières sont souvent exigés." },
        { title: 'Pertes financières', text: "Dégâts sur les stocks, sur les équipements ou sur le bâti, arrêts d'activité, amendes : une infestation non maîtrisée peut coûter très cher. Investir dans la prévention et le traitement limite ces coûts." },
        { title: 'Assurer la sécurité et le confort des employés', text: 'Un environnement sain et sans nuisibles améliore les conditions de travail et réduit le stress et les conflits liés aux infestations. Vos équipes peuvent se concentrer sur leur activité en toute sérénité.' },
        { title: 'Plans de lutte anti-nuisibles personnalisés', text: "Chaque secteur et chaque site ont leurs spécificités. Un professionnel adapte les méthodes, les fréquences d'intervention et les produits à votre activité et à la configuration de vos locaux." },
        { title: 'Suivi et maintenance continus', text: "La lutte anti-nuisibles ne se limite pas à une intervention ponctuelle. Un suivi régulier et des rapports détaillés permettent de détecter rapidement tout problème et de prouver votre démarche en cas de contrôle." },
        { title: 'Solutions écologiques', text: "Il est possible de privilégier des méthodes et des produits respectueux de l'environnement et moins agressifs pour les occupants, tout en restant efficaces. De plus en plus d'entreprises font ce choix pour aligner activité et responsabilité." },
      ],
      conclusionParagraph: "Faire appel à un expert en lutte anti-nuisibles pour votre entreprise, c'est protéger votre activité, vos équipes et vos clients. Un diagnostic et un plan d'action adaptés vous permettent d'agir en amont et de rester conforme. N'attendez pas une crise pour vous équiper.",
    },
  },
  {
    slug: 'comment-garder-votre-maison-sans-nuisible-toute-lannee',
    title: "Comment garder votre maison sans nuisible toute l'année",
    date: '15 Jan. 2026', category: 'Conseils anti-nuisibles', readMinutes: 3,
    image: '/nettoyage-maison.webp',
    content: {
      introHeading: "Garder votre maison sans nuisible : conseils essentiels",
      introParagraph: "Pour éviter les infestations, une approche régulière et quelques bonnes habitudes suffisent souvent à limiter les entrées et les sources de nourriture des nuisibles. Voici un processus simple à mettre en place tout au long de l'année.",
      numberedItems: [
        { title: "Colmatez les points d'entrée", text: "Fissures, joints abîmés, grilles de ventilation ou gaines : les nuisibles profitent des moindres accès. Inspectez régulièrement les pourtours de portes et fenêtres, les bas de murs et les zones humides, et rebouchez ou posez des grilles fines pour limiter les entrées." },
        { title: 'Nettoyage régulier', text: "Crumbs, résidus alimentaires et eau stagnante attirent les insectes et les rongeurs. Un nettoyage régulier des plans de travail, des placards et des sols, ainsi qu'une poubelle bien fermée et vidée souvent, réduisent fortement les risques." },
        { title: 'Gestion appropriée des déchets', text: "Poubelles avec couvercle, sacs bien fermés et bac à compost éloigné du bâti et couvert limitent les odeurs et l'accès à la nourriture. En extérieur, évitez d'entreposer des cartons ou des tas de bois contre les murs." },
        { title: 'Utilisez des traitements préventifs', text: "En complément de l'hygiène, des traitements préventifs peuvent être conseillés par un professionnel pour les zones à risque (combles, sous-sol, périphérie)." },
        { title: "Entretenez votre jardin", text: "Haies et végétation trop proches des murs, tas de feuilles ou de bois, et eau stagnante favorisent les nuisibles. En maintenant les abords dégagés et en évitant les réserves d'eau à ciel ouvert, vous réduisez les refuges et les points d'entrée." },
        { title: 'Installez des moustiquaires aux fenêtres', text: "En période chaude, les moustiquaires empêchent les insectes volants d'entrer tout en laissant circuler l'air. Vérifiez qu'elles sont bien fixées et sans déchirure." },
        { title: 'Surveillez les premiers signes', text: "Crottes, traces de rongement, bruits dans les cloisons ou les combles, nids ou essaims : en réagissant dès les premiers indices, vous limitez l'ampleur du problème et le coût de l'intervention." },
      ],
      conclusionTitle: 'Conclusion',
      conclusionParagraph: "Une maison bien entretenue, des points d'entrée colmatés et une hygiène régulière constituent la base d'un environnement sans nuisible. En ajoutant quelques gestes préventifs et une vigilance sur les premiers signes, vous préservez le confort de votre foyer toute l'année.",
    },
  },
  {
    slug: 'signes-dune-infestation-de-nuisibles-a-ne-pas-ignorer',
    title: "Signes d'une infestation de nuisibles à ne pas ignorer",
    date: '9 Fév. 2026', category: 'Services de lutte anti-nuisibles', readMinutes: 4,
    image: '/invasion-rat.webp',
    content: {
      introHeading: "Reconnaître les premiers signes d'une infestation de nuisibles",
      introParagraph: "Plus une infestation est détectée tôt, plus elle est facile et économique à traiter. Voici les signaux d'alerte les plus courants à surveiller chez vous ou dans vos locaux, et les bons réflexes à adopter.",
      numberedItems: [
        { title: 'Bruits inhabituels', text: "Grattements dans les murs, les plafonds ou les combles, surtout la nuit, peuvent indiquer la présence de rongeurs ou d'insectes dans les structures." },
        { title: 'Déjections', text: "Crottes de souris ou de rats, fientes d'insectes ou traces similaires près des denrées, des placards ou des zones de passage sont un indicateur fiable d'activité." },
        { title: 'Dégâts matériels', text: "Câbles rongés, emballages percés, cartons ou tissus abîmés, trous dans les plinthes ou les cloisons : les rongeurs et certains insectes laissent des traces visibles." },
        { title: 'Traces ou rongeurs visibles', text: "Empreintes dans la poussière, traces de gras le long des murs, ou observation directe d'un animal : dès que la présence est avérée, il est temps d'agir." },
        { title: 'Odeurs étranges', text: "Une odeur musquée, ammoniaquée ou nauséabonde peut signaler une population importante de rongeurs ou d'insectes. À ne pas ignorer, surtout si elle persiste ou s'accentue." },
        { title: 'Allergies inexpliquées', text: "Acariens, blattes ou déjections de nuisibles peuvent aggraver les allergies et les problèmes respiratoires." },
        { title: 'Matériaux de nidification', text: "Papiers déchiquetés, tissus, isolant arraché ou amas de matériaux dans un coin sombre sont souvent utilisés par les rongeurs pour construire leur nid." },
        { title: 'Nourriture endommagée', text: "Sachets ou boîtes percés, graines ou denrées grignotées : la cuisine et les réserves sont des cibles prioritaires." },
      ],
      conclusionTitle: 'Conclusion',
      conclusionParagraph: "Les signes d'une infestation sont souvent discrets au début. En restant attentif aux bruits, aux déjections, aux dégâts et aux odeurs, vous pouvez réagir tôt et limiter les dégâts.",
    },
  },
  {
    slug: 'destruction-nid-guepes-frelons-quand-intervenir',
    title: 'Destruction de nid de guêpes ou frelons : quand intervenir ?',
    date: '18 Nov. 2025', category: 'Guêpes et frelons', readMinutes: 3,
    image: '/nid-abeilles.png',
    content: {
      introHeading: 'Nid de guêpes ou de frelons : réagir au bon moment',
      introParagraph: "Un nid de guêpes ou de frelons à proximité de votre habitation peut représenter un risque. Savoir quand et comment intervenir permet de limiter les piqûres.",
      numberedItems: [
        { title: 'Identifier le type de nid', text: "Les guêpes et les frelons construisent des nids en papier. Faites identifier par un professionnel." },
        { title: 'Ne pas intervenir soi-même', text: "Tenter de détruire un nid sans équipement expose à des piqûres multiples. Faites appel à un professionnel." },
        { title: 'Intervenir tôt', text: "Plus le nid est petit, plus l'intervention est simple. Contactez un spécialiste dès que vous repérez un nid." },
      ],
      conclusionParagraph: "En cas de nid de guêpes ou de frelons, faites intervenir un professionnel pour une neutralisation en toute sécurité.",
    },
  },
  {
    slug: 'deratisation-particuliers-professionnels',
    title: 'Dératisation : particuliers et professionnels',
    date: '28 Nov. 2025', category: 'Dératisation', readMinutes: 4,
    image: '/invasion-insectes-interieur.png',
    content: {
      introHeading: 'Dératisation : une nécessité pour tous',
      introParagraph: "Les rats et les souris peuvent s'inviter chez les particuliers comme dans les locaux professionnels. La dératisation repose sur un diagnostic et un suivi adaptés.",
      numberedItems: [
        { title: 'Diagnostic et identification', text: "Un professionnel identifie les espèces, repère les points d'entrée et choisit les bons appâts et pièges." },
        { title: 'Mise en place du traitement', text: "La dératisation combine appâts sécurisés, pièges et colmatage des accès. Les produits sont placés hors de portée des enfants et des animaux." },
        { title: 'Suivi et prévention', text: "Un suivi régulier permet d'éviter les réinfestations. Des conseils d'hygiène complètent l'intervention." },
      ],
      conclusionParagraph: "Une dératisation réalisée par un expert garantit un résultat durable. N'attendez pas une infestation importante pour agir.",
    },
  },
  {
    slug: 'punaises-de-lit-protocole-traitement',
    title: 'Punaises de lit : protocole de traitement',
    date: '5 Déc. 2025', category: 'Punaises de lit', readMinutes: 4,
    image: '/punaises-de-lit.webp',
    content: {
      introHeading: 'Éliminer les punaises de lit : méthode et rigueur',
      introParagraph: "Les punaises de lit nécessitent un traitement méthodique. Un protocole adapté, souvent en plusieurs passages, permet de s'en débarrasser durablement.",
      numberedItems: [
        { title: 'Diagnostic des foyers', text: "Le professionnel repère les zones infestées (literie, canapé, plinthes). Une inspection minutieuse permet de cibler tous les foyers." },
        { title: 'Traitement des zones de repos', text: "Le traitement vise les zones où les punaises se cachent et pondent. Les produits sont adaptés aux punaises de lit." },
        { title: 'Conseils post-traitement', text: "Laver le linge à haute température, suivre les conseils pour limiter les retours." },
      ],
      conclusionParagraph: "Une infestation de punaises de lit ne se règle pas avec des produits en libre-service. Un protocole professionnel est indispensable.",
    },
  },
  {
    slug: 'chenilles-processionnaires-risques-traitement',
    title: 'Chenilles processionnaires : risques et traitement',
    date: '14 Jan. 2026', category: 'Chenilles processionnaires', readMinutes: 3,
    image: '/chenilles-processionnaires.jpg',
    content: {
      introHeading: 'Chenilles processionnaires : un risque pour les humains et les animaux',
      introParagraph: "Les chenilles processionnaires du pin et du chêne sont urticantes. Leurs poils peuvent provoquer des réactions cutanées. Les animaux sont particulièrement exposés.",
      numberedItems: [
        { title: 'Reconnaître les nids', text: "Les nids blancs et soyeux dans les pins sont typiques. Les processions au sol sont un autre signe. Faites identifier par un professionnel." },
        { title: 'Destruction des nids', text: "Un professionnel peut détruire les nids en sécurité et proposer un traitement préventif." },
        { title: 'Protéger les animaux', text: "Évitez que chiens et chats s'approchent des zones infestées. En cas de contact, consultez un vétérinaire." },
      ],
      conclusionParagraph: "Une intervention professionnelle protège votre famille et vos animaux.",
    },
  },
  {
    slug: 'cafards-blattes-desinsectisation',
    title: 'Cafards et blattes : désinsectisation efficace',
    date: '28 Jan. 2026', category: 'Désinsectisation', readMinutes: 3,
    image: '/invasion-cafards.png',
    content: {
      introHeading: 'Éliminer les cafards et blattes durablement',
      introParagraph: "Les cafards et blattes prolifèrent dans les cuisines et les endroits humides. Une désinsectisation ciblée et des mesures d'hygiène permettent de s'en débarrasser.",
      numberedItems: [
        { title: 'Identifier espèces et zones', text: "L'identification permet d'adapter le traitement. Les zones de passage et les nids sont repérés." },
        { title: 'Traitement par gel ou appâts', text: "Les professionnels utilisent des gels ou des appâts que les blattes rapportent au nid." },
        { title: 'Hygiène et étanchéité', text: "Réduire les sources de nourriture, colmater les fentes limitent les réinfestations." },
      ],
      conclusionParagraph: "Faites appel à un expert pour un diagnostic et un plan d'action.",
    },
  },
  {
    slug: 'fourmis-invasion-prevention',
    title: 'Fourmis : en finir avec les invasions',
    date: '4 Fév. 2026', category: 'Désinsectisation', readMinutes: 3,
    image: '/fourmis.png',
    content: {
      introHeading: 'Lutter contre les fourmis dans la maison',
      introParagraph: "Les fourmis peuvent devenir envahissantes en période chaude. Traiter les pistes et les points d'entrée permet de réduire les invasions.",
      numberedItems: [
        { title: 'Repérer les pistes et nids', text: "Les fourmis suivent des pistes régulières. En repérant ces pistes, on peut remonter vers les points d'entrée." },
        { title: 'Traitement ciblé', text: "Gels et appâts placés sur les pistes permettent aux fourmis de rapporter le produit au nid." },
        { title: 'Prévention', text: "Colmater les fissures, garder les plans de travail propres limite les entrées." },
      ],
      conclusionParagraph: "Un traitement ciblé et une bonne prévention permettent de limiter les invasions. Contactez un professionnel.",
    },
  },
  {
    slug: 'moustique-tigre-prevention-printemps-2026',
    title: 'Moustique tigre : prévention et nouveaux enjeux pour le printemps 2026',
    date: '3 Avr. 2026', category: 'Moustiques', readMinutes: 5,
    image: '/moustique-tigre-2026.webp',
    content: {
      introHeading: 'Le moustique tigre : un envahisseur discret mais préoccupant',
      introParagraph: "Originaire d'Asie du Sud-Est, le moustique tigre (Aedes albopictus) s'est désormais bien implanté en France. Plus petit que le moustique commun, il se distingue par ses rayures noires et blanches et son vol silencieux à basse altitude. Voici comment limiter sa présence et s'en protéger dès le début du printemps.",
      numberedItems: [
        { title: 'Adopter la lutte préventive (suppression des gîtes larvaires)', text: "La femelle pond jusqu'à 200 œufs dans des eaux stagnantes. Même une infime quantité suffit. Videz régulièrement les soucoupes, seaux, pneus, et nettoyez vos gouttières." },
        { title: 'Prudence avec la lutte chimique et les méthodes alternatives', text: "L'utilisation anarchique d'insecticides est néfaste pour la biodiversité, tuant également les prédateurs naturels du moustique." },
        { title: 'Favoriser les prédateurs naturels', text: "Les prédateurs comme les oiseaux insectivores, les chauves-souris, ou certaines araignées consomment des moustiques. Les accueillir aide à l'équilibre général du jardin." },
        { title: 'Solutions matérielles ciblées de nouvelle génération', text: "Les pièges pondoirs écologiques de nouvelle génération ciblent les femelles en quête de ponte. Les moustiquaires aux fenêtres restent un des rares barrages individuels vraiment efficaces." },
      ],
      conclusionParagraph: "La lutte contre le moustique tigre repose d'abord sur une action préventive collective. Une infestation installée peut nécessiter le diagnostic ou le renfort professionnel.",
    },
  },
];

export const seedServices = [
  {
    slug: 'lutte-anti-nuisibles-pour-particuliers',
    title: 'Lutte anti-nuisibles complète pour les particuliers',
    description: 'Protégez votre maison des nuisibles grâce à nos services sur mesure qui ciblent et éliminent efficacement les indésirables.',
    image: '/nid-abeilles.png',
    heroSubtitle: 'Des solutions efficaces et respectueuses de l\'environnement pour protéger votre foyer des nuisibles dans les Bouches-du-Rhône.',
    content: {
      intro: 'Votre maison est un refuge pour vous et votre famille. Nous vous aidons à le garder sain et sûr en éliminant les nuisibles de manière durable et en mettant en place des mesures préventives adaptées.',
      whyTitle: 'Pourquoi Action Nuisibles 13 pour votre maison ?',
      whyItems: [
        { title: 'Techniciens experts', text: 'Notre équipe est hautement qualifiée et formée aux dernières techniques de lutte anti-nuisibles, pour un résultat optimal et durable.' },
        { title: 'Traitements sûrs et écologiques', text: "Nous accordons la priorité à la sécurité de votre famille et de vos animaux. Nos produits et méthodes respectent l'environnement tout en restant très efficaces." },
        { title: 'Mesures préventives', text: "En plus de traiter les infestations existantes, nous mettons en place des actions préventives pour limiter les risques de retour des nuisibles." },
      ],
      processTitle: "Notre processus d'intervention",
      processSteps: [
        { title: 'Inspection', text: "Nos professionnels commencent par une inspection complète de votre habitation pour identifier les nuisibles, les zones à risque et les points d'entrée." },
        { title: 'Plan de traitement personnalisé', text: "Sur la base de nos observations, nous définissons un plan de traitement adapté à votre situation et à vos contraintes." },
        { title: 'Suivi et maintenance confirmés', text: "Après le traitement initial, nous assurons un suivi et des conseils de maintenance pour garantir une protection durable." },
      ],
      ctaText: "Contactez-nous pour planifier une intervention ou obtenir un devis personnalisé.",
    },
  },
  {
    slug: 'solutions-anti-nuisibles-entreprises',
    title: 'Solutions anti-nuisibles pour les entreprises',
    description: "Protégez votre activité avec nos services anti-nuisibles spécialisés, pour éviter toute perturbation et garantir un environnement sûr et sain.",
    image: '/nuisibles-solution-pro.png',
    heroSubtitle: "Protégez votre activité avec nos services anti-nuisibles spécialisés, pour éviter toute perturbation et garantir un environnement sain et sûr.",
    content: {
      intro: "Protégez votre entreprise grâce à nos services spécialisés de lutte anti-nuisibles. Action Nuisibles 13 accompagne les professionnels des Bouches-du-Rhône avec une expertise reconnue et des interventions conformes aux normes sanitaires.",
      whyTitle: "Pourquoi Action Nuisibles 13 est votre partenaire de confiance ?",
      whyItems: [
        { title: 'Solutions anti-nuisibles complètes', text: "De l'inspection à la prévention, nous couvrons l'ensemble des besoins des professionnels : rongeurs, insectes, guêpes et frelons, chenilles processionnaires, et nuisibles occasionnels." },
        { title: 'Perturbations minimales', text: "Nous intervenons en dehors des heures d'ouverture si besoin et utilisons des méthodes qui limitent la gêne pour votre activité." },
        { title: 'Conformité aux normes sanitaires', text: "Nos interventions respectent la réglementation en vigueur. Nous fournissons les documents et rapports nécessaires pour vos contrôles et audits." },
      ],
      processTitle: "Notre processus d'intervention pour les professionnels",
      processSteps: [
        { title: 'Inspection initiale', text: "Nous commençons par une inspection approfondie de vos locaux pour identifier les risques potentiels et les infestations actives." },
        { title: 'Plan de traitement personnalisé', text: "Nous élaborons un plan de traitement adapté à votre type d'activité, en utilisant des méthodes de lutte anti-nuisibles sûres et efficaces." },
        { title: 'Suivi continu et rapports', text: "Notre service inclut un suivi régulier pour détecter tout nouveau problème, ainsi que des rapports détaillés pour vous tenir informé." },
      ],
      ctaText: "Contactez Action Nuisibles 13 dès aujourd'hui pour une consultation ou un devis adapté à votre activité.",
    },
  },
  {
    slug: 'intervention-rapide-urgences',
    title: 'Intervention anti nuisibles rapide pour les situations urgentes',
    description: "Obtenez une intervention immédiate en cas d'infestation avec notre service d'urgence, pour assurer la sécurisation rapide de votre habitation ou de vos locaux.",
    image: '/invasion-cafards.png',
    heroSubtitle: "Obtenez une intervention immédiate en cas d'infestation, avec notre service d'urgence, pour assurer la résolution rapide de votre habitation ou de vos locaux.",
    content: {
      intro: "Une intervention rapide limite les dégâts et rétablit la sérénité. Que vous soyez confronté à un nid de guêpes ou de frelons, à une infestation de rongeurs ou d'insectes, notre équipe peut se déplacer dans les meilleurs délais.",
      whyTitle: "Pourquoi choisir Action Nuisibles 13 pour les urgences ?",
      whyItems: [
        { title: "Délai d'intervention rapide", text: "Nous nous efforçons d'intervenir sous 2h ou dans la journée selon la gravité. Nous intervenons dans les Bouches-du-Rhône." },
        { title: 'Solutions d\'urgence complètes', text: "Des rongeurs aux insectes, en passant par les guêpes et frelons ou les chenilles processionnaires : nous disposons du matériel et des protocoles pour agir sur tous les types de nuisibles." },
        { title: 'Techniciens expérimentés', text: "Nos techniciens sont formés aux interventions d'urgence et disposent des équipements de protection et des produits nécessaires pour intervenir en toute sécurité." },
      ],
      processTitle: "Notre processus d'intervention d'urgence",
      processSteps: [
        { title: 'Évaluation immédiate', text: "Lors de votre appel, nous évaluons la situation pour préparer l'intervention et vous indiquer un délai réaliste." },
        { title: 'Traitement à action rapide', text: "Notre technicien se rend sur place avec le matériel adapté et utilise des traitements à action rapide pour neutraliser le nuisible." },
        { title: 'Suivi et prévention', text: "À l'issue de l'intervention, nous vous donnons les consignes à respecter et, si besoin, planifions une visite de contrôle." },
      ],
      ctaText: "Si vous faites face à un problème urgent de nuisibles, n'attendez pas ! Contactez Action Nuisibles 13 maintenant pour un service d'urgence rapide et fiable.",
    },
  },
];

export const seedFaq = [
  { question: 'Combien coûte une intervention de dératisation ou désinsectisation ?', answer: "Le coût d'une intervention anti-nuisibles dépend du type de nuisible, de la surface à traiter et de la complexité. Nous établissons un devis gratuit après diagnostic. Nos tarifs sont transparents pour les particuliers et les professionnels dans les Bouches-du-Rhône. Contactez-nous pour un devis personnalisé." },
  { question: "Quel est le délai d'intervention pour une urgence nuisibles ?", answer: "Nous nous efforçons d'intervenir sous 2h ou dans la journée selon la gravité pour les urgences (nid de guêpes, frelons, infestation importante) dans les Bouches-du-Rhône." },
  { question: 'Proposez-vous une garantie après un traitement anti-nuisibles ?', answer: "Oui. Nous nous engageons sur l'efficacité de nos traitements. En cas de réinfestation dans le délai convenu, nous réintervenons selon les conditions de notre garantie." },
  { question: 'Vos traitements sont-ils sans danger pour les enfants et les animaux ?', answer: "Oui. Nous privilégions des produits certifiés, respectueux de l'environnement et sans danger pour votre famille et vos animaux. La sécurité des occupants est une priorité dans toutes nos interventions." },
  { question: 'Quels nuisibles traitez-vous ?', answer: "Nous traitons les rongeurs (rats, souris), les insectes (cafards, blattes, fourmis, punaises de lit, puces), les guêpes et frelons (y compris frelon asiatique), les chenilles processionnaires du pin et du chêne." },
  { question: 'Comment se déroule une intervention de dératisation ?', answer: "La dératisation comprend une inspection des lieux pour identifier les rongeurs et les points d'entrée, la pose d'appâts ou de pièges sécurisés, le colmatage des accès et un suivi pour vérifier l'élimination." },
  { question: 'Comment se déroule une désinsectisation ?', answer: "La désinsectisation débute par un diagnostic. Nous appliquons ensuite un traitement ciblé (pulvérisation, gel, fumigation selon les cas). Pour les punaises de lit, plusieurs passages peuvent être nécessaires." },
  { question: 'Faut-il quitter les lieux pendant le traitement ?', answer: "Cela dépend du type d'intervention et des produits utilisés. Nos techniciens vous informent clairement avant chaque intervention sur les délais d'évacuation et d'aération nécessaires." },
  { question: 'Comment se débarrasser des punaises de lit ?', answer: "L'élimination des punaises de lit nécessite un protocole rigoureux : diagnostic, traitement insecticide ciblé (souvent plusieurs passages), et conseils (lavage du linge, housses). L'autotraitement est souvent insuffisant." },
  { question: 'Que faire en cas de nid de guêpes ou de frelons ?', answer: "Ne tentez pas de détruire le nid vous-même : le risque de piqûres multiples est élevé. Contactez un professionnel pour une destruction ou une neutralisation du nid en toute sécurité." },
  { question: 'Comment reconnaître une infestation de rongeurs ?', answer: "Les signes d'une infestation incluent : crottes, traces de passage, bruits dans les cloisons ou les combles, câbles ou emballages rongés, odeurs. Un diagnostic par un professionnel permet de confirmer et d'agir." },
  { question: 'Que sont les chenilles processionnaires et comment les traiter ?', answer: "Les chenilles processionnaires sont des nuisibles dont les poils urticants peuvent provoquer des réactions chez l'homme et les animaux. Nous proposons la destruction des nids et des traitements préventifs." },
  { question: 'Intervenez-vous pour les professionnels (restaurants, commerces) ?', answer: "Oui. Nous intervenons auprès des professionnels : restaurants, commerces, entrepôts, établissements de santé, collectivités. Nous adaptons nos interventions aux contraintes d'hygiène et de conformité." },
  { question: 'Dans quelles villes et communes intervenez-vous ?', answer: "Nous intervenons dans les Bouches-du-Rhône : Marseille, Martigues, Aubagne, Aix-en-Provence, Vitrolles, Marignane, La Ciotat, Cassis, Fos-sur-Mer, Port-de-Bouc, et de nombreuses autres communes de la région PACA." },
  { question: 'Comment obtenir un devis gratuit pour une dératisation ou désinsectisation ?', answer: "Vous pouvez nous contacter par téléphone ou via le formulaire de contact. Nous vous posons quelques questions et pouvons organiser une visite pour un diagnostic. Le devis est gratuit et sans engagement." },
  { question: 'Utilisez-vous des produits écologiques pour la lutte anti-nuisibles ?', answer: "Nous privilégions des méthodes et des produits respectueux de l'environnement lorsque c'est possible, sans compromis sur l'efficacité. Les produits utilisés sont homologués et appliqués selon les normes." },
  { question: 'Combien de temps dure un traitement contre les nuisibles ?', answer: "La durée varie selon le nuisible et l'ampleur de l'infestation. Une intervention sur un nid de guêpes peut être réalisée en une fois. Une dératisation ou désinsectisation peut nécessiter plusieurs passages et un suivi." },
  { question: "Que faire après une intervention anti-nuisibles ?", answer: "Nous vous remettons des conseils de prévention : colmater les points d'entrée, gérer les déchets et le stockage, éviter les sources de nourriture accessibles, maintenir la propreté." },
  { question: "Comment prévenir une réinfestation de rongeurs ou d'insectes ?", answer: "Colmater les fissures et accès, garder les denrées dans des contenants fermés, évacuer les déchets régulièrement, éviter le bois et les cartons contre les murs, maintenir les espaces propres." },
  { question: "Proposez-vous des contrats d'entretien ou d'abonnement ?", answer: "Oui. Nous proposons des formules d'entretien pour les particuliers et surtout les professionnels : interventions programmées, rapports, réactivité en cas d'urgence. Idéal pour les restaurants et commerces." },
  { question: 'Quelle est la différence entre dératisation et désinsectisation ?', answer: "La dératisation vise l'élimination des rongeurs par pièges, appâts et sécurisation des accès. La désinsectisation concerne les insectes nuisibles avec des traitements insecticides ciblés." },
  { question: 'Frelon asiatique : que faire et qui contacter ?', answer: "Le frelon asiatique peut construire des nids volumineux et représente un risque. Ne tentez pas de détruire le nid vous-même. Contactez un professionnel. Nous intervenons dans les Bouches-du-Rhône." },
  { question: 'Nid de guêpes dans le mur ou sous le toit : qui contacter ?', answer: "Un nid de guêpes dans un mur, sous un toit ou dans un arbre doit être traité par un professionnel. Nous intervenons avec protection et matériel adaptés. Intervention possible en urgence." },
  { question: 'Punaises de lit : une seule intervention suffit-elle ?', answer: "Souvent non. Un protocole comprend généralement plusieurs passages et des conseils (linge, literie, mobilier). Nous établissons un plan de traitement après diagnostic." },
  { question: 'Cafards et blattes : comment les éliminer durablement ?', answer: "L'élimination passe par un diagnostic, un traitement insecticide adapté (gel, appâts, pulvérisation) et des recommandations d'hygiène et de colmatage. Une désinsectisation professionnelle est plus efficace." },
  { question: 'Quel réflexe adopter en cas d\'invasion de nuisibles ?', answer: "Évitez l'autotraitement avec des produits en libre-service. Contactez un professionnel pour un diagnostic et un devis. Pour un nid de guêpes ou de frelons, ne tentez pas de le détruire vous-même." },
];
